#############################################################################
# Makefile for building: WriteDisk
# Generated by qmake (2.01a) (Qt 4.8.7) on: ?? 8? 24 15:38:28 2021
# Project:  WriteDisk.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o Makefile WriteDisk.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_MULTIMEDIA_LIB -DQT_SQL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtSql -I/usr/include/qt4/QtMultimedia -I/usr/include/qt4 -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtMultimedia -lQtSql -lQtGui -lQtCore -lasound -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		widget.cpp \
		iic_pthread.cpp \
		page_pthread.cpp \
		led.cpp \
		music.cpp \
		audiothread.cpp \
		aplay_pthread.cpp \
		sqlite3.cpp \
		dispNetStatus.cpp moc_widget.cpp \
		moc_iic_pthread.cpp \
		moc_page_pthread.cpp \
		moc_audiothread.cpp \
		moc_aplay_pthread.cpp \
		moc_dispNetStatus.cpp
OBJECTS       = main.o \
		widget.o \
		iic_pthread.o \
		page_pthread.o \
		led.o \
		music.o \
		audiothread.o \
		aplay_pthread.o \
		sqlite3.o \
		dispNetStatus.o \
		moc_widget.o \
		moc_iic_pthread.o \
		moc_page_pthread.o \
		moc_audiothread.o \
		moc_aplay_pthread.o \
		moc_dispNetStatus.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		WriteDisk.pro
QMAKE_TARGET  = WriteDisk
DESTDIR       = 
TARGET        = WriteDisk

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: WriteDisk.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtSql.prl \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile WriteDisk.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtSql.prl:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile WriteDisk.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/WriteDisk1.0.0 || $(MKDIR) .tmp/WriteDisk1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/WriteDisk1.0.0/ && $(COPY_FILE) --parents widget.h i2c-dev.h iic_pthread.h page_pthread.h led.h music.h audiothread.h aplay_pthread.h sqlite3.h dispNetStatus.h .tmp/WriteDisk1.0.0/ && $(COPY_FILE) --parents main.cpp widget.cpp iic_pthread.cpp page_pthread.cpp led.cpp music.cpp audiothread.cpp aplay_pthread.cpp sqlite3.cpp dispNetStatus.cpp .tmp/WriteDisk1.0.0/ && (cd `dirname .tmp/WriteDisk1.0.0` && $(TAR) WriteDisk1.0.0.tar WriteDisk1.0.0 && $(COMPRESS) WriteDisk1.0.0.tar) && $(MOVE) `dirname .tmp/WriteDisk1.0.0`/WriteDisk1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/WriteDisk1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_widget.cpp moc_iic_pthread.cpp moc_page_pthread.cpp moc_audiothread.cpp moc_aplay_pthread.cpp moc_dispNetStatus.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_widget.cpp moc_iic_pthread.cpp moc_page_pthread.cpp moc_audiothread.cpp moc_aplay_pthread.cpp moc_dispNetStatus.cpp
moc_widget.cpp: led.h \
		music.h \
		audiothread.h \
		aplay_pthread.h \
		dispNetStatus.h \
		widget.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) widget.h -o moc_widget.cpp

moc_iic_pthread.cpp: iic_pthread.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) iic_pthread.h -o moc_iic_pthread.cpp

moc_page_pthread.cpp: widget.h \
		led.h \
		music.h \
		audiothread.h \
		aplay_pthread.h \
		dispNetStatus.h \
		page_pthread.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) page_pthread.h -o moc_page_pthread.cpp

moc_audiothread.cpp: audiothread.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) audiothread.h -o moc_audiothread.cpp

moc_aplay_pthread.cpp: aplay_pthread.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) aplay_pthread.h -o moc_aplay_pthread.cpp

moc_dispNetStatus.cpp: led.h \
		music.h \
		audiothread.h \
		aplay_pthread.h \
		dispNetStatus.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) dispNetStatus.h -o moc_dispNetStatus.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp iic_pthread.h \
		page_pthread.h \
		widget.h \
		led.h \
		music.h \
		audiothread.h \
		aplay_pthread.h \
		dispNetStatus.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

widget.o: widget.cpp widget.h \
		led.h \
		music.h \
		audiothread.h \
		aplay_pthread.h \
		dispNetStatus.h \
		sqlite3.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o widget.o widget.cpp

iic_pthread.o: iic_pthread.cpp i2c-dev.h \
		iic_pthread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o iic_pthread.o iic_pthread.cpp

page_pthread.o: page_pthread.cpp i2c-dev.h \
		page_pthread.h \
		widget.h \
		led.h \
		music.h \
		audiothread.h \
		aplay_pthread.h \
		dispNetStatus.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o page_pthread.o page_pthread.cpp

led.o: led.cpp led.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o led.o led.cpp

music.o: music.cpp music.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o music.o music.cpp

audiothread.o: audiothread.cpp audiothread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o audiothread.o audiothread.cpp

aplay_pthread.o: aplay_pthread.cpp aplay_pthread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o aplay_pthread.o aplay_pthread.cpp

sqlite3.o: sqlite3.cpp sqlite3.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sqlite3.o sqlite3.cpp

dispNetStatus.o: dispNetStatus.cpp widget.h \
		led.h \
		music.h \
		audiothread.h \
		aplay_pthread.h \
		dispNetStatus.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dispNetStatus.o dispNetStatus.cpp

moc_widget.o: moc_widget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_widget.o moc_widget.cpp

moc_iic_pthread.o: moc_iic_pthread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_iic_pthread.o moc_iic_pthread.cpp

moc_page_pthread.o: moc_page_pthread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_page_pthread.o moc_page_pthread.cpp

moc_audiothread.o: moc_audiothread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_audiothread.o moc_audiothread.cpp

moc_aplay_pthread.o: moc_aplay_pthread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_aplay_pthread.o moc_aplay_pthread.cpp

moc_dispNetStatus.o: moc_dispNetStatus.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dispNetStatus.o moc_dispNetStatus.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

